#cloud-config
packages:
  - curl
  - openssh-server
  - ufw
package_reboot_if_required: false
package_update: false
runcmd:
  # Secure SSHD
  - [rm, -f, /root/.ssh/authorized_keys]
  # Secure UFW
  - ufw allow ssh
  - ufw enable
  # Install Docker
  - if docker ; then echo "Docker already installed"; else curl -fsSL https://get.docker.com | sh; fi
  - systemctl restart docker
timezone: UTC
users:
  - name: "{{ .Username }}"
    gecos: DevPod
    groups:
      - docker
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: true
    shell: /bin/bash
    ssh_authorized_keys:
      - "{{ .PublicKey }}"
  - name: test
    lock_passwd: false
    passwd: $1$X4rlCkR8$mZuINsPlJmSydnLeIFTl5/
    sudo: ALL=(ALL) NOPASSWD:ALL
write_files:
  - path: /etc/docker/daemon.json
    content: |
      {
        "features": {
          "buildkit": true
        },
        "live-restore": true
      }
